20250406 code updates

diff --git a/zshinit b/zshinit
--- a/zshinit
+++ b/zshinit
@@ -1,5 +1,5 @@
 # ---------------------------------------------------------
-# vim: ft=sh
+# vim: ft=zsh
 #
 # File: ./zshinit.zsh
 #
@@ -12,7 +12,7 @@
 # Check for the minimum supported version.
 min_zsh_version='4.3.11'
 autoload -Uz is-at-least && is-at-least "$min_zsh_version" || {
-    printf "Old zsh detected, minimum required: %s\n" "$min_zsh_version" >&2
+	printf "Old zsh detected, minimum required: %s\n" "$min_zsh_version" >&2
     return 1
 }
 unset min_zsh_version
@@ -43,37 +43,37 @@ function pmodload {
     for pmodule in ${pmodules}; do
         # Skip if module is already loaded
         zstyle -t ":e4czmod:module:$pmodule" loaded 'yes' 'no' && continue
-    
+
         # Find module locations
         locations=(${pmodule_dirs:+${^pmodule_dirs}/$pmodule(-/FN)})
-    
+
         # Handle module location cases
         case ${#locations} in
-            0) 
+            0)
                 print "$0: no such module: $pmodule"
                 continue
                 ;;
-            1) 
+            1)
                 ;;
-            *) 
+            *)
                 zstyle -t ':e4czmod:load' pmodule-allow-overrides 'yes' || {
                     print "$0: conflicting module locations: $locations"
                     continue
                 }
                 ;;
         esac
-    
+
         # Grab the full path to this module.
         pmodule_location=${locations[1]}
-        
+
         # Add functions to $fpath.
         fpath=(${pmodule_location}/functions(-/FN) $fpath)
-        
+
         # Load functions using anonymous function
         () {
             # Extended globbing is needed for listing autoloadable function directories.
             setopt LOCAL_OPTIONS EXTENDED_GLOB
-            
+
             # Load functions.
             for pfunction in ${pmodule_location}/functions/$~pfunction_glob; do
                 autoload -Uz "$pfunction"
@@ -95,18 +95,18 @@ function pmodload {
         } || {
             # Clean up on failure
             fpath[(r)${pmodule_location}/functions]=()
-            
+
             # Load functions using anonymous function
             () {
                 # Extended globbing is needed for listing autoloadable function directories.
                 setopt LOCAL_OPTIONS EXTENDED_GLOB
-                
+
                 # Load functions.
                 for pfunction in ${pmodule_location}/functions/$~pfunction_glob; do
                     autoload -Uz "$pfunction"
                 done
             }
-        
+
             zstyle ":e4czmod:module:$pmodule" loaded 'no'
         }
     done
